
package com.kwetter.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GoPlusServiceImpl", targetNamespace = "http://soap.kwetter.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GoPlusServiceImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createTweet", targetNamespace = "http://soap.kwetter.com/", className = "com.kwetter.soap.CreateTweet")
    @ResponseWrapper(localName = "createTweetResponse", targetNamespace = "http://soap.kwetter.com/", className = "com.kwetter.soap.CreateTweetResponse")
    @Action(input = "http://soap.kwetter.com/GoPlusServiceImpl/createTweetRequest", output = "http://soap.kwetter.com/GoPlusServiceImpl/createTweetResponse")
    public void createTweet(
        @WebParam(name = "arg0", targetNamespace = "")
        SimpleTweet arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.kwetter.soap.SimpleTweet>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeline", targetNamespace = "http://soap.kwetter.com/", className = "com.kwetter.soap.GetTimeline")
    @ResponseWrapper(localName = "getTimelineResponse", targetNamespace = "http://soap.kwetter.com/", className = "com.kwetter.soap.GetTimelineResponse")
    @Action(input = "http://soap.kwetter.com/GoPlusServiceImpl/getTimelineRequest", output = "http://soap.kwetter.com/GoPlusServiceImpl/getTimelineResponse")
    public List<SimpleTweet> getTimeline(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
