
package com.kwetter.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GoPlusService", targetNamespace = "http://soap.kwetter.com/", wsdlLocation = "http://localhost:15509/kwetter/GoPlusService?wsdl")
public class GoPlusService
    extends Service
{

    private final static URL GOPLUSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GOPLUSSERVICE_EXCEPTION;
    private final static QName GOPLUSSERVICE_QNAME = new QName("http://soap.kwetter.com/", "GoPlusService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:15509/kwetter/GoPlusService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GOPLUSSERVICE_WSDL_LOCATION = url;
        GOPLUSSERVICE_EXCEPTION = e;
    }

    public GoPlusService() {
        super(__getWsdlLocation(), GOPLUSSERVICE_QNAME);
    }

    public GoPlusService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GOPLUSSERVICE_QNAME, features);
    }

    public GoPlusService(URL wsdlLocation) {
        super(wsdlLocation, GOPLUSSERVICE_QNAME);
    }

    public GoPlusService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GOPLUSSERVICE_QNAME, features);
    }

    public GoPlusService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GoPlusService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GoPlusServiceImpl
     */
    @WebEndpoint(name = "GoPlusServiceImplPort")
    public GoPlusServiceImpl getGoPlusServiceImplPort() {
        return super.getPort(new QName("http://soap.kwetter.com/", "GoPlusServiceImplPort"), GoPlusServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GoPlusServiceImpl
     */
    @WebEndpoint(name = "GoPlusServiceImplPort")
    public GoPlusServiceImpl getGoPlusServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.kwetter.com/", "GoPlusServiceImplPort"), GoPlusServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GOPLUSSERVICE_EXCEPTION!= null) {
            throw GOPLUSSERVICE_EXCEPTION;
        }
        return GOPLUSSERVICE_WSDL_LOCATION;
    }

}
